---
language: python
services: docker

env:
  global:
    - ROLE_NAME: backup
  matrix:
    - TEST_PLATFORM: centos:7
    - TEST_PLATFORM: ubuntu:16.04
    - TEST_PLATFORM: ubuntu:18.04

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME newtonne.$ROLE_NAME
  - cd newtonne.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
