---
- name: Include OS-specific variables (Debian)
  include_vars: "{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat)
  include_vars: "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == 'RedHat'

- import_tasks: install-borg.yml

- import_tasks: install-borgmatic.yml

- import_tasks: configure.yml

- import_tasks: cleanup.yml
